name: CI Pipeline

# Step 2: Trigger workflow on pull requests to main
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Using an action â€“ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 4: Running commands
      - name: Install Dependencies
        run: npm install

      # Linting step
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run Jest tests
      - name: Run Jest Tests
        run: npm test -- --coverage
